### ISSUE TITLE
Ledger wallets

### ISSUE THREAD

**Issue by StevenBlack** [BitcoinQnA/bitcoin-wallet-guide#2]
Hi 👋 is there a reason no Ledger wallets are mentioned yet?  

My guess: no reason, it's just early days; the repo is barely a week old.

Presuming that's right, would you entertain contributions?

**Comment by BitcoinQnA** [comment]
Hi, no Ledger mentioned as they do not offer a Bitcoin only firmware option (see #4 of feature criteria).

I also don't want to push users toward a company that allows [this](https://www.coindesk.com/crypto-wallet-ledger-email-addresses-data-theft).

Contributions absolutely welcomed.

**Comment by StevenBlack** [comment]
@BitcoinQnA I understand.  I didn't figure that "bitcoin only" would ever be a feature or criteria.  I see now that this is stated.

Actually the criteria [`2. Be open source`](https://bitcoinwallet.guide/) applies here as well, and overrides all.

Closing.
